# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\Base Folder\Workspace\AI\Alpaca\alpaca.cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\Base Folder\Workspace\AI\Alpaca\alpaca.cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Base Folder\Workspace\AI\Alpaca\alpaca.cpp\CMakeFiles" "D:\Base Folder\Workspace\AI\Alpaca\alpaca.cpp\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Base Folder\Workspace\AI\Alpaca\alpaca.cpp\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chat

# Build rule for target.
chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 chat
.PHONY : chat

# fast build rule for target.
chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/build
.PHONY : chat/fast

#=============================================================================
# Target rules for targets named quantize

# Build rule for target.
quantize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 quantize
.PHONY : quantize

# fast build rule for target.
quantize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/build
.PHONY : quantize/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ggml.dir\build.make CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

chat.obj: chat.cpp.obj
.PHONY : chat.obj

# target to build an object file
chat.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/chat.cpp.obj
.PHONY : chat.cpp.obj

chat.i: chat.cpp.i
.PHONY : chat.i

# target to preprocess a source file
chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/chat.cpp.i
.PHONY : chat.cpp.i

chat.s: chat.cpp.s
.PHONY : chat.s

# target to generate assembly for a file
chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/chat.cpp.s
.PHONY : chat.cpp.s

ggml.obj: ggml.c.obj
.PHONY : ggml.obj

# target to build an object file
ggml.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ggml.dir\build.make CMakeFiles/ggml.dir/ggml.c.obj
.PHONY : ggml.c.obj

ggml.i: ggml.c.i
.PHONY : ggml.i

# target to preprocess a source file
ggml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ggml.dir\build.make CMakeFiles/ggml.dir/ggml.c.i
.PHONY : ggml.c.i

ggml.s: ggml.c.s
.PHONY : ggml.s

# target to generate assembly for a file
ggml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ggml.dir\build.make CMakeFiles/ggml.dir/ggml.c.s
.PHONY : ggml.c.s

quantize.obj: quantize.cpp.obj
.PHONY : quantize.obj

# target to build an object file
quantize.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/quantize.cpp.obj
.PHONY : quantize.cpp.obj

quantize.i: quantize.cpp.i
.PHONY : quantize.i

# target to preprocess a source file
quantize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/quantize.cpp.i
.PHONY : quantize.cpp.i

quantize.s: quantize.cpp.s
.PHONY : quantize.s

# target to generate assembly for a file
quantize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/quantize.cpp.s
.PHONY : quantize.cpp.s

utils.obj: utils.cpp.obj
.PHONY : utils.obj

# target to build an object file
utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/utils.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/utils.cpp.obj
.PHONY : utils.cpp.obj

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\chat.dir\build.make CMakeFiles/chat.dir/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\quantize.dir\build.make CMakeFiles/quantize.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... chat
	@echo ... ggml
	@echo ... quantize
	@echo ... chat.obj
	@echo ... chat.i
	@echo ... chat.s
	@echo ... ggml.obj
	@echo ... ggml.i
	@echo ... ggml.s
	@echo ... quantize.obj
	@echo ... quantize.i
	@echo ... quantize.s
	@echo ... utils.obj
	@echo ... utils.i
	@echo ... utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

